#
# Build our container to run the Python script that downloads comments.
#

FROM alpine:latest

RUN apk add bash python3

RUN mkdir /app

COPY requirements.txt /app
RUN pip3 install -r /app/requirements.txt

COPY bin/download* /app/
COPY entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]

